server:
  port: 8083
spring:
  application:
    name: cart-microservice
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/postgres
    username: postgres
    password: ""
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:8761/eureka}
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate.type.descriptor.BasicBinder: trace
